// lang-gr.ts

export const LANG_GR_NAME = 'gr';

export const LANG_GR_TRANS = {
    'title': 'Ταξί Γεωργιούπολης',
    'home': 'Αρχική Σελίδα',
    'bookTransfer': 'Κάντε Κράτηση',
    'tours': 'Διαδρομές',
    'prices': 'Τιμές',
    'about': 'Σχετικά',
    'language': 'Γλώσσες',
    'english': 'Αγγλικά',
    'greek': 'Ελληνικά',
    'search': 'Αναζήτηση',

    'georgioupolis': 'Γεωργιούπολη',
    'footerDescription': 'Το προσωπικό μας είναι διαθέσιμο για εσάς. Για περισσότερες πληροφορίες παρακαλώ επικοινωνίστε μαζί μας. Εγγυόμαστε άμμεση ανταπόκριση προκειμένου να σας παρέχουμε όσες περισσότερες πληροφορίες μπορούμε. Μην διστάσετε.',
    'creteGreece': 'Κρήτη, Ελλάδα',
    'myName': 'Ξενάκης Νικόλαος',
    'copyrightsReserved': 'Όλα τα δικαιώματα είναι καταχωρημένα.',

    'motoString': 'Ασφαλής και Αξιόπιστη μεταφορά',

    'indexCarouselTitle1': 'Το καλύτερο ξεκίνημα!',
    'indexCarouselDescription1': 'Δεσμευόμαστε για την μεταφορά σας από και προς κάθε αεροδρόμιο της Κρήτης',
    'indexCarouselTitle2': 'Αξιόπιστη, γρήγορη και άνετη μετακίνηση',
    'indexCarouselDescription2': 'Πεπειραμένοι οδηγοί διαθέσιμοι 24/7',
    'indexCarouselTitle3': 'Ασφαλής και οικονομική μετακίνηση',
    'indexCarouselDescription3': 'Για εσάς και την οικογένεια σας από και πρός κάθε προορισμό στην Κρήτη',
    'indexCarouselTitle4': 'Ανακαλύψτε',
    'indexCarouselDescription4': 'Κάντε κράτηση προς μυστικές τοποθεσίες στην Κρήτη',
    'bookTransferDescription': "Είναι εύκολο, γρήγορο και δωρεάν, κάντε κράτηση online άμεσα, τα υπόλοιπα αφήστε τα πάνω μας!",

    'personalInfo': 'Προσωπικές Πληροφορίες',
    'firstName': 'Όνομα',
    'lastName': 'Επώνυμο',
    'email': 'Email',
    'invalidFirstName': 'Σφάλμα Ονόματος',
    'enterFirstName': 'Εισάγετε όνομα',
    'invalidLastName': 'Σφάλμα επώνυμου',
    'enterLastName': 'Εισάγετε επώνυμο',
    'invalidEmail': 'Σφάλμα email',
    'enterEmail': 'Εισάγετε email',
    'passengersDetails': 'Πληροφορίες επιβατών',
    'passengers': 'Επιβάτες',
    'select': 'Επιλέξτε...',
    'babySheat': 'Παιδικό κάθισμα',
    'tripDetails': 'Πληροφορίες Ταξιδιού',
    'meetingPoint': 'Αφετηρία',
    'time': 'Ώρα',
    'date': 'Ημερομηνία',
    'bookTransferMessage': 'Η κράτηση ήταν επιτυχής. Θα λάβετε mail επιβεβαίωσης με τις πληροφορίες μετακίνησης.',
    'firstNamePlaceholder': 'π.χ. Γιάννης',
    'lastNamePlaceholder': 'π.χ. Αγγελόπουλος',
    'emailPlaceholder': 'π.χ. aggelGian2@gmail.com',
    'meetingPoingPlaceholder': 'προσθέστε αφετηρία...',
    'destinationPlaceholder': 'προσθέστε προορισμό...',
    'datePlaceholder': 'προσθέστε ημ/νία...',
    'comments': 'Σχόλια',
    
    'toursDescription': 'Προσφέρουμε μια εντελώς νέα ταξιδιωτική εμπειρία. Τώρα έχετε την δυνατότητα να κάνε κράτηση για ένα από τα μοναδικά μας πακέτα ξενάγησής. Σας ταξιδεύουμε απο μυστικές τοποθεσίες σε παραδοσιακούς χώρους με σπιτικό Κρητικό φαγητό στην περιοχή των Χανίων. Ενδιαφέρεστε? Τα πακέτα διακοπών προσαρμόζονται ανάλογα το τι ψάχνετε. Για περαιτέρω πληροφορίες παρακαλώ επικοινωνήστε μαζί μας.',
    
    'priceTable': 'Τιμοκατάλογος',
    'priceTableDescription': 'Ανταγωνιστικές Τιμές με online κρατήσεις από τα αεροδρόμια Χανίων και Ηρακλείου πρός τους δημοφιλέστερους προορισμούς της Κρήτης.',
    'bookNow': 'Κάντε Κράτηση',
    'destination': 'Προορισμός',
    'priceEuros': 'Τιμή',
    'distanceKm': 'Απόσταση',
    'durationHours': 'Διάρκεια',
    'priceTableDetails': '*Οι τιμές ισχύουν από/προς τα αεροδρόμια Χανίων και Ηρακλείου',
    'chaniaPriceTableTitle': 'Αεροδρόμιο Χανίων',
    'heraklionPriceTableTitle': 'Αεροδρόμιο Ηρακλείου',
};