// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'title': 'Georgioupolis Transfers',
    'home': 'Home',
    'bookTransfer': 'Book Transfer',
    'tours': 'Tours',
    'prices': 'Prices',
    'about': 'About',
    'language': 'Language',
    'english': 'English',
    'greek': 'Greek',
    'search': 'Search',

    'georgioupolis': 'Georgioupolis',
    'footerDescription': 'Our stuff is always available for you. For any futher information please contact us. We guarandee immidiate response in order to provide you as much information as we can. Please don\'t hesitate.',
    'creteGreece': 'Crete, Greece',
    'myName': 'Xenakis Nikolaos',
    'copyrightsReserved': 'All copyrights reserved.',

    'motoString': 'Secure and Reliable transportation',

    'indexCarouselTitle1': 'The best start!',
    'indexCarouselDescription1': 'We commit for your transfer from and to each airpot of Crete',
    'indexCarouselTitle2': 'Reliable, fast and cozy',
    'indexCarouselDescription2': 'Using experienced english speaking drivers available for you 24/7',
    'indexCarouselTitle3': 'Secure and cheap transportation',
    'indexCarouselDescription3': 'For you and your family from and to any destination in the island of Crete',
    'indexCarouselTitle4': 'Discover',
    'indexCarouselDescription4': 'Book tours to secret locations around Crete',
    'bookTransferDescription': "It's easy, quick and free, book your transfer online now, we will \"run\" instead of you!",

    'personalInfo': 'Pesonal Info',
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'email': 'Email',
    'invalidFirstName': 'Invalid first name',
    'enterFirstName': 'Enter your first name',
    'invalidLastName': 'Invalid last name',
    'enterLastName': 'Enter your last name',
    'invalidEmail': 'Invalid email',
    'enterEmail': 'Enter your email',
    'passengersDetails': 'Passengers Details',
    'passengers': 'Passengers',
    'select': 'Select...',
    'babySheat': 'Baby Sheat',
    'tripDetails': 'Trip Details',
    'meetingPoint': 'Meeting Point',
    'time': 'Time',
    'date': 'Date',
    'bookTransferMessage': 'You have successfully booked your transfer. You will receive a confirmation email with the tranfer details.',
    'firstNamePlaceholder': 'e.g Jonathan',
    'lastNamePlaceholder': 'e.g Morris',
    'emailPlaceholder': 'e.g morris34@gmail.com',
    'meetingPoingPlaceholder': 'add meeting point...',
    'destinationPlaceholder': 'add destination...',
    'datePlaceholder': 'add date...',
    'comments': 'Comments',

    'toursDescription': 'Georgioupolis Transfers offers a whole new section in holidays experience. You are able to book one of our unique tour packages. Georgioupolis Trasfers Tours guides you from extrordinary locations to traditional places with homemade Cretan food in the region of Chania. Are you interested? The tour packages adjust depending what you are looking for. For further information contact us.',

    'priceTable': 'Pricetable',
    'priceTableDescription': 'Competitive Prices for online booking from Georgioupolis to the most visited destinations in Crete.',
    'bookNow': 'Book Now',
    'destination': 'Destination',
    'priceEuros': 'Price',
    'distanceKm': 'Distance',
    'durationHours': 'Duration',
    'priceTableDetails': '*The prices are from/to Georgioupolis',
};